name: xylophone
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  audioplayers: ^0.15.1

  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - note1.wav
    - note2.wav
    - note3.wav
    - note4.wav
    - note5.wav
    - note6.wav
    - note7.wav

